### PR TITLE
hide horizontal overflow (prevents annoying sideways scrollbars on mobile)

### PR DESCRIPTION
**Pull request by shoshber**

### CODE REVIEW

**Comment by orlando** [comment]
I don't see that in mobile 

gif

**Comment by shoshber** [comment]
I noticed it while looking at the power report

**Comment by orlando** [comment]
@shoshber then why you are opening a PR in the `discourse-debtcollective-theme`?

**Comment by shoshber** [comment]
Isn't this the repo for the style we pull from S3?

**Pull request closed without merging**
